name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - 'backend/lambda/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Zip Lambda
        run: |
          cd backend/lambda/visit_count
          zip -r ../visit_count.zip .

      - name: Deploy Lambda
        run: |
          aws lambda update-function-code \
            --function-name aravadhikari-visitcount-function \
            --zip-file fileb://backend/lambda/visit_count.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-west-1
